//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Permission
    {
        public dnn_Permission()
        {
            this.dnn_FolderPermission = new HashSet<dnn_FolderPermission>();
            this.dnn_ModulePermission = new HashSet<dnn_ModulePermission>();
            this.dnn_TabPermission = new HashSet<dnn_TabPermission>();
        }
    
        public int PermissionID { get; set; }
        public string PermissionCode { get; set; }
        public int ModuleDefID { get; set; }
        public string PermissionKey { get; set; }
        public string PermissionName { get; set; }
    
        public virtual ICollection<dnn_FolderPermission> dnn_FolderPermission { get; set; }
        public virtual ICollection<dnn_ModulePermission> dnn_ModulePermission { get; set; }
        public virtual ICollection<dnn_TabPermission> dnn_TabPermission { get; set; }
    }
}
