//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_SearchItemWord
    {
        public dnn_SearchItemWord()
        {
            this.dnn_SearchItemWordPosition = new HashSet<dnn_SearchItemWordPosition>();
        }
    
        public int SearchItemWordID { get; set; }
        public int SearchItemID { get; set; }
        public int SearchWordsID { get; set; }
        public int Occurrences { get; set; }
    
        public virtual dnn_SearchItem dnn_SearchItem { get; set; }
        public virtual dnn_SearchWord dnn_SearchWord { get; set; }
        public virtual ICollection<dnn_SearchItemWordPosition> dnn_SearchItemWordPosition { get; set; }
    }
}
