//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_SearchItem
    {
        public dnn_SearchItem()
        {
            this.dnn_SearchItemWord = new HashSet<dnn_SearchItemWord>();
        }
    
        public int SearchItemID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Author { get; set; }
        public System.DateTime PubDate { get; set; }
        public int ModuleId { get; set; }
        public string SearchKey { get; set; }
        public string Guid { get; set; }
        public Nullable<int> HitCount { get; set; }
        public Nullable<int> ImageFileId { get; set; }
    
        public virtual dnn_Modules dnn_Modules { get; set; }
        public virtual ICollection<dnn_SearchItemWord> dnn_SearchItemWord { get; set; }
    }
}
