//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_YourCompany_LogEntry
    {
        public Nullable<int> ModuleID { get; set; }
        public int ItemID { get; set; }
        public string Entry { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    
        public virtual dnn_Modules dnn_Modules { get; set; }
    }
}
