//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_ModuleDefinitions
    {
        public dnn_ModuleDefinitions()
        {
            this.dnn_ModuleControls = new HashSet<dnn_ModuleControls>();
            this.dnn_Modules = new HashSet<dnn_Modules>();
        }
    
        public int ModuleDefID { get; set; }
        public string FriendlyName { get; set; }
        public int DesktopModuleID { get; set; }
        public int DefaultCacheTime { get; set; }
    
        public virtual dnn_DesktopModules dnn_DesktopModules { get; set; }
        public virtual ICollection<dnn_ModuleControls> dnn_ModuleControls { get; set; }
        public virtual ICollection<dnn_Modules> dnn_Modules { get; set; }
    }
}
