//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Classification
    {
        public dnn_Classification()
        {
            this.dnn_Classification1 = new HashSet<dnn_Classification>();
            this.dnn_VendorClassification = new HashSet<dnn_VendorClassification>();
        }
    
        public int ClassificationId { get; set; }
        public string ClassificationName { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual ICollection<dnn_Classification> dnn_Classification1 { get; set; }
        public virtual dnn_Classification dnn_Classification2 { get; set; }
        public virtual ICollection<dnn_VendorClassification> dnn_VendorClassification { get; set; }
    }
}
