//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_UserDefinedData
    {
        public int UserDefinedFieldId { get; set; }
        public int UserDefinedRowId { get; set; }
        public string FieldValue { get; set; }
    
        public virtual dnn_UserDefinedFields dnn_UserDefinedFields { get; set; }
        public virtual dnn_UserDefinedRows dnn_UserDefinedRows { get; set; }
    }
}
