//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Blog_Entries
    {
        public dnn_Blog_Entries()
        {
            this.dnn_Blog_Comments = new HashSet<dnn_Blog_Comments>();
        }
    
        public int BlogID { get; set; }
        public int EntryID { get; set; }
        public string Title { get; set; }
        public string Entry { get; set; }
        public System.DateTime AddedDate { get; set; }
        public bool Published { get; set; }
        public string Description { get; set; }
        public Nullable<bool> AllowComments { get; set; }
        public bool DisplayCopyright { get; set; }
        public string Copyright { get; set; }
        public string PermaLink { get; set; }
    
        public virtual ICollection<dnn_Blog_Comments> dnn_Blog_Comments { get; set; }
    }
}
