//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_grmRepositoryObjects
    {
        public int ItemID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedByUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public string AuthorEmail { get; set; }
        public string FileSize { get; set; }
        public Nullable<int> Downloads { get; set; }
        public string PreviewImage { get; set; }
        public string Image { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Clicks { get; set; }
        public Nullable<long> RatingVotes { get; set; }
        public Nullable<long> RatingTotal { get; set; }
        public Nullable<double> RatingAverage { get; set; }
        public Nullable<int> Approved { get; set; }
        public Nullable<int> ShowEMail { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
    }
}
