//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Wiki_Settings
    {
        public int SettingID { get; set; }
        public int ModuleID { get; set; }
        public string ContentEditorRoles { get; set; }
        public bool AllowDiscussions { get; set; }
        public bool AllowRatings { get; set; }
    }
}
