//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Documents
    {
        public int ItemID { get; set; }
        public int ModuleID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string URL { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public Nullable<int> CreatedByUserID { get; set; }
        public Nullable<int> OwnedByUserID { get; set; }
        public Nullable<int> ModifiedByUserID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> SortOrderIndex { get; set; }
        public string Description { get; set; }
    
        public virtual dnn_Modules dnn_Modules { get; set; }
    }
}
