//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Folders
    {
        public dnn_Folders()
        {
            this.dnn_Files = new HashSet<dnn_Files>();
            this.dnn_FolderPermission = new HashSet<dnn_FolderPermission>();
        }
    
        public int FolderID { get; set; }
        public Nullable<int> PortalID { get; set; }
        public string FolderPath { get; set; }
        public int StorageLocation { get; set; }
        public bool IsProtected { get; set; }
        public bool IsCached { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual ICollection<dnn_Files> dnn_Files { get; set; }
        public virtual ICollection<dnn_FolderPermission> dnn_FolderPermission { get; set; }
        public virtual dnn_Portals dnn_Portals { get; set; }
    }
}
