//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_UserDefinedRows
    {
        public dnn_UserDefinedRows()
        {
            this.dnn_UserDefinedData = new HashSet<dnn_UserDefinedData>();
        }
    
        public int UserDefinedRowId { get; set; }
        public int ModuleId { get; set; }
    
        public virtual dnn_Modules dnn_Modules { get; set; }
        public virtual ICollection<dnn_UserDefinedData> dnn_UserDefinedData { get; set; }
    }
}
