//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Tabs
    {
        public dnn_Tabs()
        {
            this.dnn_TabModules = new HashSet<dnn_TabModules>();
            this.dnn_TabPermission = new HashSet<dnn_TabPermission>();
            this.dnn_Tabs1 = new HashSet<dnn_Tabs>();
        }
    
        public int TabID { get; set; }
        public int TabOrder { get; set; }
        public Nullable<int> PortalID { get; set; }
        public string TabName { get; set; }
        public bool IsVisible { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int Level { get; set; }
        public string IconFile { get; set; }
        public bool DisableLink { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string KeyWords { get; set; }
        public bool IsDeleted { get; set; }
        public string Url { get; set; }
        public string SkinSrc { get; set; }
        public string ContainerSrc { get; set; }
        public string TabPath { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> RefreshInterval { get; set; }
        public string PageHeadText { get; set; }
        public bool IsSecure { get; set; }
    
        public virtual dnn_Portals dnn_Portals { get; set; }
        public virtual ICollection<dnn_TabModules> dnn_TabModules { get; set; }
        public virtual ICollection<dnn_TabPermission> dnn_TabPermission { get; set; }
        public virtual ICollection<dnn_Tabs> dnn_Tabs1 { get; set; }
        public virtual dnn_Tabs dnn_Tabs2 { get; set; }
    }
}
