//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Events
    {
        public dnn_Events()
        {
            this.dnn_EventsNotification = new HashSet<dnn_EventsNotification>();
            this.dnn_EventsSignups = new HashSet<dnn_EventsSignups>();
        }
    
        public int EventID { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<System.DateTime> EventDateBegin { get; set; }
        public Nullable<System.DateTime> EventDateEnd { get; set; }
        public Nullable<System.DateTime> EventTimeBegin { get; set; }
        public Nullable<int> Duration { get; set; }
        public string EventName { get; set; }
        public string EventDesc { get; set; }
        public Nullable<int> Importance { get; set; }
        public string RepeatType { get; set; }
        public string Every { get; set; }
        public string Period { get; set; }
        public string Reminder { get; set; }
        public string Notify { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<int> PortalID { get; set; }
        public Nullable<bool> Signups { get; set; }
        public Nullable<int> MaxEnrollment { get; set; }
        public string EnrollRoleID { get; set; }
        public Nullable<decimal> EnrollFee { get; set; }
        public string EnrollType { get; set; }
        public string PayPalAccount { get; set; }
        public string PayPalPassword { get; set; }
        public Nullable<bool> Cancelled { get; set; }
        public string ImageURL { get; set; }
        public string ImageType { get; set; }
        public Nullable<int> ImageWidth { get; set; }
        public Nullable<int> ImageHeight { get; set; }
        public Nullable<bool> ImageDisplay { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> TimezoneOffset { get; set; }
        public Nullable<bool> SendReminder { get; set; }
        public Nullable<int> ReminderTime { get; set; }
        public string ReminderTimeMeasurement { get; set; }
        public string ReminderFrom { get; set; }
        public Nullable<bool> SearchSubmitted { get; set; }
    
        public virtual dnn_Modules dnn_Modules { get; set; }
        public virtual ICollection<dnn_EventsNotification> dnn_EventsNotification { get; set; }
        public virtual ICollection<dnn_EventsSignups> dnn_EventsSignups { get; set; }
    }
}
