//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Help_Tutorials
    {
        public string ProductImage { get; set; }
        public bool Featured { get; set; }
        public string KeyWords { get; set; }
        public string DownloadName { get; set; }
        public string ShortDesc { get; set; }
        public bool Archive { get; set; }
        public string Description { get; set; }
        public int TutorialID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.Guid> TutorialGUID { get; set; }
        public Nullable<int> ModuleID { get; set; }
    }
}
