//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Users
    {
        public dnn_Users()
        {
            this.dnn_Blog_Blogs = new HashSet<dnn_Blog_Blogs>();
            this.dnn_FolderPermission = new HashSet<dnn_FolderPermission>();
            this.dnn_ModulePermission = new HashSet<dnn_ModulePermission>();
            this.dnn_Profile = new HashSet<dnn_Profile>();
            this.dnn_TabPermission = new HashSet<dnn_TabPermission>();
            this.dnn_UserAuthentication = new HashSet<dnn_UserAuthentication>();
            this.dnn_UserPortals = new HashSet<dnn_UserPortals>();
            this.dnn_UserProfile = new HashSet<dnn_UserProfile>();
            this.dnn_UserRoles = new HashSet<dnn_UserRoles>();
            this.dnn_UsersOnline = new HashSet<dnn_UsersOnline>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsSuperUser { get; set; }
        public Nullable<int> AffiliateId { get; set; }
        public string Email { get; set; }
        public string DisplayName { get; set; }
        public bool UpdatePassword { get; set; }
    
        public virtual ICollection<dnn_Blog_Blogs> dnn_Blog_Blogs { get; set; }
        public virtual ICollection<dnn_FolderPermission> dnn_FolderPermission { get; set; }
        public virtual ICollection<dnn_ModulePermission> dnn_ModulePermission { get; set; }
        public virtual ICollection<dnn_Profile> dnn_Profile { get; set; }
        public virtual ICollection<dnn_TabPermission> dnn_TabPermission { get; set; }
        public virtual ICollection<dnn_UserAuthentication> dnn_UserAuthentication { get; set; }
        public virtual ICollection<dnn_UserPortals> dnn_UserPortals { get; set; }
        public virtual ICollection<dnn_UserProfile> dnn_UserProfile { get; set; }
        public virtual ICollection<dnn_UserRoles> dnn_UserRoles { get; set; }
        public virtual ICollection<dnn_UsersOnline> dnn_UsersOnline { get; set; }
    }
}
