//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_TabModules
    {
        public dnn_TabModules()
        {
            this.dnn_TabModuleSettings = new HashSet<dnn_TabModuleSettings>();
        }
    
        public int TabModuleID { get; set; }
        public int TabID { get; set; }
        public int ModuleID { get; set; }
        public string PaneName { get; set; }
        public int ModuleOrder { get; set; }
        public int CacheTime { get; set; }
        public string Alignment { get; set; }
        public string Color { get; set; }
        public string Border { get; set; }
        public string IconFile { get; set; }
        public int Visibility { get; set; }
        public string ContainerSrc { get; set; }
        public bool DisplayTitle { get; set; }
        public bool DisplayPrint { get; set; }
        public bool DisplaySyndicate { get; set; }
    
        public virtual dnn_Modules dnn_Modules { get; set; }
        public virtual dnn_Tabs dnn_Tabs { get; set; }
        public virtual ICollection<dnn_TabModuleSettings> dnn_TabModuleSettings { get; set; }
    }
}
