//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Xml_Parameter
    {
        public int ParameterID { get; set; }
        public int ModuleID { get; set; }
        public string Purpose { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Argument { get; set; }
        public bool ValueIsRequired { get; set; }
    }
}
