//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Help_Category
    {
        public int CategoryID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Image { get; set; }
        public string KeyWords { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public int Order { get; set; }
        public int Level { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.Guid> CategoryGUID { get; set; }
    }
}
