//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Roles
    {
        public dnn_Roles()
        {
            this.dnn_UserRoles = new HashSet<dnn_UserRoles>();
        }
    
        public int RoleID { get; set; }
        public int PortalID { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> ServiceFee { get; set; }
        public string BillingFrequency { get; set; }
        public Nullable<int> TrialPeriod { get; set; }
        public string TrialFrequency { get; set; }
        public Nullable<int> BillingPeriod { get; set; }
        public Nullable<decimal> TrialFee { get; set; }
        public bool IsPublic { get; set; }
        public bool AutoAssignment { get; set; }
        public Nullable<int> RoleGroupID { get; set; }
        public string RSVPCode { get; set; }
        public string IconFile { get; set; }
    
        public virtual dnn_Portals dnn_Portals { get; set; }
        public virtual dnn_RoleGroups dnn_RoleGroups { get; set; }
        public virtual ICollection<dnn_UserRoles> dnn_UserRoles { get; set; }
    }
}
