//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_UrlTracking
    {
        public dnn_UrlTracking()
        {
            this.dnn_UrlLog = new HashSet<dnn_UrlLog>();
        }
    
        public int UrlTrackingID { get; set; }
        public Nullable<int> PortalID { get; set; }
        public string Url { get; set; }
        public string UrlType { get; set; }
        public int Clicks { get; set; }
        public Nullable<System.DateTime> LastClick { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool LogActivity { get; set; }
        public bool TrackClicks { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public bool NewWindow { get; set; }
    
        public virtual dnn_Portals dnn_Portals { get; set; }
        public virtual ICollection<dnn_UrlLog> dnn_UrlLog { get; set; }
    }
}
