//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Vendors
    {
        public dnn_Vendors()
        {
            this.dnn_Affiliates = new HashSet<dnn_Affiliates>();
            this.dnn_Banners = new HashSet<dnn_Banners>();
            this.dnn_VendorClassification = new HashSet<dnn_VendorClassification>();
        }
    
        public int VendorId { get; set; }
        public string VendorName { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string PostalCode { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> PortalId { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public int ClickThroughs { get; set; }
        public int Views { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string LogoFile { get; set; }
        public string KeyWords { get; set; }
        public string Unit { get; set; }
        public bool Authorized { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Cell { get; set; }
    
        public virtual ICollection<dnn_Affiliates> dnn_Affiliates { get; set; }
        public virtual ICollection<dnn_Banners> dnn_Banners { get; set; }
        public virtual dnn_Portals dnn_Portals { get; set; }
        public virtual ICollection<dnn_VendorClassification> dnn_VendorClassification { get; set; }
    }
}
