//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_EventLogConfig
    {
        public dnn_EventLogConfig()
        {
            this.dnn_EventLog = new HashSet<dnn_EventLog>();
        }
    
        public int ID { get; set; }
        public string LogTypeKey { get; set; }
        public Nullable<int> LogTypePortalID { get; set; }
        public bool LoggingIsActive { get; set; }
        public int KeepMostRecent { get; set; }
        public bool EmailNotificationIsActive { get; set; }
        public Nullable<int> NotificationThreshold { get; set; }
        public Nullable<int> NotificationThresholdTime { get; set; }
        public Nullable<int> NotificationThresholdTimeType { get; set; }
        public string MailFromAddress { get; set; }
        public string MailToAddress { get; set; }
    
        public virtual ICollection<dnn_EventLog> dnn_EventLog { get; set; }
        public virtual dnn_EventLogTypes dnn_EventLogTypes { get; set; }
    }
}
