//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Portals
    {
        public dnn_Portals()
        {
            this.dnn_AnonymousUsers = new HashSet<dnn_AnonymousUsers>();
            this.dnn_Blog_Blogs = new HashSet<dnn_Blog_Blogs>();
            this.dnn_EventsCategory = new HashSet<dnn_EventsCategory>();
            this.dnn_EventsLocation = new HashSet<dnn_EventsLocation>();
            this.dnn_Files = new HashSet<dnn_Files>();
            this.dnn_Folders = new HashSet<dnn_Folders>();
            this.dnn_Modules = new HashSet<dnn_Modules>();
            this.dnn_PortalAlias = new HashSet<dnn_PortalAlias>();
            this.dnn_PortalDesktopModules = new HashSet<dnn_PortalDesktopModules>();
            this.dnn_Profile = new HashSet<dnn_Profile>();
            this.dnn_ProfilePropertyDefinition = new HashSet<dnn_ProfilePropertyDefinition>();
            this.dnn_RoleGroups = new HashSet<dnn_RoleGroups>();
            this.dnn_Roles = new HashSet<dnn_Roles>();
            this.dnn_SiteLog = new HashSet<dnn_SiteLog>();
            this.dnn_Skins = new HashSet<dnn_Skins>();
            this.dnn_SystemMessages = new HashSet<dnn_SystemMessages>();
            this.dnn_Tabs = new HashSet<dnn_Tabs>();
            this.dnn_Urls = new HashSet<dnn_Urls>();
            this.dnn_UrlTracking = new HashSet<dnn_UrlTracking>();
            this.dnn_UserPortals = new HashSet<dnn_UserPortals>();
            this.dnn_UsersOnline = new HashSet<dnn_UsersOnline>();
            this.dnn_Vendors = new HashSet<dnn_Vendors>();
        }
    
        public int PortalID { get; set; }
        public string PortalName { get; set; }
        public string LogoFile { get; set; }
        public string FooterText { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int UserRegistration { get; set; }
        public int BannerAdvertising { get; set; }
        public Nullable<int> AdministratorId { get; set; }
        public string Currency { get; set; }
        public decimal HostFee { get; set; }
        public int HostSpace { get; set; }
        public Nullable<int> AdministratorRoleId { get; set; }
        public Nullable<int> RegisteredRoleId { get; set; }
        public string Description { get; set; }
        public string KeyWords { get; set; }
        public string BackgroundFile { get; set; }
        public System.Guid GUID { get; set; }
        public string PaymentProcessor { get; set; }
        public string ProcessorUserId { get; set; }
        public string ProcessorPassword { get; set; }
        public Nullable<int> SiteLogHistory { get; set; }
        public Nullable<int> HomeTabId { get; set; }
        public Nullable<int> LoginTabId { get; set; }
        public Nullable<int> UserTabId { get; set; }
        public string DefaultLanguage { get; set; }
        public int TimezoneOffset { get; set; }
        public Nullable<int> AdminTabId { get; set; }
        public string HomeDirectory { get; set; }
        public Nullable<int> SplashTabId { get; set; }
        public int PageQuota { get; set; }
        public int UserQuota { get; set; }
    
        public virtual ICollection<dnn_AnonymousUsers> dnn_AnonymousUsers { get; set; }
        public virtual ICollection<dnn_Blog_Blogs> dnn_Blog_Blogs { get; set; }
        public virtual ICollection<dnn_EventsCategory> dnn_EventsCategory { get; set; }
        public virtual ICollection<dnn_EventsLocation> dnn_EventsLocation { get; set; }
        public virtual ICollection<dnn_Files> dnn_Files { get; set; }
        public virtual ICollection<dnn_Folders> dnn_Folders { get; set; }
        public virtual ICollection<dnn_Modules> dnn_Modules { get; set; }
        public virtual ICollection<dnn_PortalAlias> dnn_PortalAlias { get; set; }
        public virtual ICollection<dnn_PortalDesktopModules> dnn_PortalDesktopModules { get; set; }
        public virtual ICollection<dnn_Profile> dnn_Profile { get; set; }
        public virtual ICollection<dnn_ProfilePropertyDefinition> dnn_ProfilePropertyDefinition { get; set; }
        public virtual ICollection<dnn_RoleGroups> dnn_RoleGroups { get; set; }
        public virtual ICollection<dnn_Roles> dnn_Roles { get; set; }
        public virtual ICollection<dnn_SiteLog> dnn_SiteLog { get; set; }
        public virtual ICollection<dnn_Skins> dnn_Skins { get; set; }
        public virtual ICollection<dnn_SystemMessages> dnn_SystemMessages { get; set; }
        public virtual ICollection<dnn_Tabs> dnn_Tabs { get; set; }
        public virtual ICollection<dnn_Urls> dnn_Urls { get; set; }
        public virtual ICollection<dnn_UrlTracking> dnn_UrlTracking { get; set; }
        public virtual ICollection<dnn_UserPortals> dnn_UserPortals { get; set; }
        public virtual ICollection<dnn_UsersOnline> dnn_UsersOnline { get; set; }
        public virtual ICollection<dnn_Vendors> dnn_Vendors { get; set; }
    }
}
