//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Media
    {
        public int ModuleID { get; set; }
        public string Src { get; set; }
        public string alt { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
        public string NavigateUrl { get; set; }
        public Nullable<int> MediaAlignment { get; set; }
    
        public virtual dnn_Modules dnn_Modules { get; set; }
    }
}
