//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_SurveyOptions
    {
        public dnn_SurveyOptions()
        {
            this.dnn_SurveyResults = new HashSet<dnn_SurveyResults>();
        }
    
        public int SurveyOptionID { get; set; }
        public int SurveyID { get; set; }
        public int ViewOrder { get; set; }
        public string OptionName { get; set; }
        public int Votes { get; set; }
        public bool IsCorrect { get; set; }
    
        public virtual dnn_Surveys dnn_Surveys { get; set; }
        public virtual ICollection<dnn_SurveyResults> dnn_SurveyResults { get; set; }
    }
}
