//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Blog_Blogs
    {
        public int PortalID { get; set; }
        public int BlogID { get; set; }
        public int UserID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Public { get; set; }
        public bool AllowComments { get; set; }
        public bool AllowAnonymous { get; set; }
        public Nullable<System.DateTime> LastEntry { get; set; }
        public System.DateTime Created { get; set; }
        public bool ShowFullName { get; set; }
        public string DateFormat { get; set; }
        public string Culture { get; set; }
        public int TimeZone { get; set; }
        public Nullable<int> ParentBlogID { get; set; }
        public bool Syndicated { get; set; }
        public bool SyndicateIndependant { get; set; }
        public string SyndicationURL { get; set; }
        public string SyndicationEmail { get; set; }
        public Nullable<bool> EmailNotification { get; set; }
        public Nullable<bool> AllowTrackbacks { get; set; }
        public Nullable<bool> AutoTrackback { get; set; }
        public Nullable<bool> MustApproveComments { get; set; }
        public Nullable<bool> MustApproveAnonymous { get; set; }
        public Nullable<bool> MustApproveTrackbacks { get; set; }
        public Nullable<bool> UseCaptcha { get; set; }
    
        public virtual dnn_Portals dnn_Portals { get; set; }
        public virtual dnn_Users dnn_Users { get; set; }
    }
}
