//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Wiki_Topic
    {
        public int TopicID { get; set; }
        public int ModuleID { get; set; }
        public string Content { get; set; }
        public string Cache { get; set; }
        public string Name { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdatedBy { get; set; }
        public int UpdatedByUserID { get; set; }
        public bool AllowDiscussions { get; set; }
        public bool AllowRatings { get; set; }
        public int RatingOneCount { get; set; }
        public int RatingTwoCount { get; set; }
        public int RatingThreeCount { get; set; }
        public int RatingFourCount { get; set; }
        public int RatingFiveCount { get; set; }
        public int RatingSixCount { get; set; }
        public int RatingSevenCount { get; set; }
        public int RatingEightCount { get; set; }
        public int RatingNineCount { get; set; }
        public int RatingTenCount { get; set; }
    }
}
