//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Modules
    {
        public dnn_Modules()
        {
            this.dnn_Announcements = new HashSet<dnn_Announcements>();
            this.dnn_Documents = new HashSet<dnn_Documents>();
            this.dnn_Events = new HashSet<dnn_Events>();
            this.dnn_EventsMaster = new HashSet<dnn_EventsMaster>();
            this.dnn_FAQs = new HashSet<dnn_FAQs>();
            this.dnn_Links = new HashSet<dnn_Links>();
            this.dnn_ModulePermission = new HashSet<dnn_ModulePermission>();
            this.dnn_ModuleSettings = new HashSet<dnn_ModuleSettings>();
            this.dnn_SearchItem = new HashSet<dnn_SearchItem>();
            this.dnn_Surveys = new HashSet<dnn_Surveys>();
            this.dnn_TabModules = new HashSet<dnn_TabModules>();
            this.dnn_UserDefinedFields = new HashSet<dnn_UserDefinedFields>();
            this.dnn_UserDefinedRows = new HashSet<dnn_UserDefinedRows>();
            this.dnn_YourCompany_HelloWorld = new HashSet<dnn_YourCompany_HelloWorld>();
            this.dnn_YourCompany_LogEntry = new HashSet<dnn_YourCompany_LogEntry>();
        }
    
        public int ModuleID { get; set; }
        public int ModuleDefID { get; set; }
        public string ModuleTitle { get; set; }
        public bool AllTabs { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> InheritViewPermissions { get; set; }
        public string Header { get; set; }
        public string Footer { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> PortalID { get; set; }
    
        public virtual ICollection<dnn_Announcements> dnn_Announcements { get; set; }
        public virtual ICollection<dnn_Documents> dnn_Documents { get; set; }
        public virtual dnn_DocumentsSettings dnn_DocumentsSettings { get; set; }
        public virtual ICollection<dnn_Events> dnn_Events { get; set; }
        public virtual ICollection<dnn_EventsMaster> dnn_EventsMaster { get; set; }
        public virtual ICollection<dnn_FAQs> dnn_FAQs { get; set; }
        public virtual dnn_HtmlText dnn_HtmlText { get; set; }
        public virtual ICollection<dnn_Links> dnn_Links { get; set; }
        public virtual dnn_Media dnn_Media { get; set; }
        public virtual dnn_ModuleDefinitions dnn_ModuleDefinitions { get; set; }
        public virtual ICollection<dnn_ModulePermission> dnn_ModulePermission { get; set; }
        public virtual dnn_Portals dnn_Portals { get; set; }
        public virtual ICollection<dnn_ModuleSettings> dnn_ModuleSettings { get; set; }
        public virtual ICollection<dnn_SearchItem> dnn_SearchItem { get; set; }
        public virtual ICollection<dnn_Surveys> dnn_Surveys { get; set; }
        public virtual ICollection<dnn_TabModules> dnn_TabModules { get; set; }
        public virtual ICollection<dnn_UserDefinedFields> dnn_UserDefinedFields { get; set; }
        public virtual ICollection<dnn_UserDefinedRows> dnn_UserDefinedRows { get; set; }
        public virtual ICollection<dnn_YourCompany_HelloWorld> dnn_YourCompany_HelloWorld { get; set; }
        public virtual ICollection<dnn_YourCompany_LogEntry> dnn_YourCompany_LogEntry { get; set; }
    }
}
