//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_Help_TutorialCategory
    {
        public int CategoryID { get; set; }
        public int ItemID { get; set; }
        public int ViewOrder { get; set; }
        public Nullable<int> TutorialID { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.Guid> TutorialCategoryGUID { get; set; }
    }
}
