//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_ProfilePropertyDefinition
    {
        public dnn_ProfilePropertyDefinition()
        {
            this.dnn_UserProfile = new HashSet<dnn_UserProfile>();
        }
    
        public int PropertyDefinitionID { get; set; }
        public Nullable<int> PortalID { get; set; }
        public Nullable<int> ModuleDefID { get; set; }
        public bool Deleted { get; set; }
        public int DataType { get; set; }
        public string DefaultValue { get; set; }
        public string PropertyCategory { get; set; }
        public string PropertyName { get; set; }
        public int Length { get; set; }
        public bool Required { get; set; }
        public string ValidationExpression { get; set; }
        public int ViewOrder { get; set; }
        public bool Visible { get; set; }
    
        public virtual dnn_Portals dnn_Portals { get; set; }
        public virtual ICollection<dnn_UserProfile> dnn_UserProfile { get; set; }
    }
}
