//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class dnn_PortalDesktopModules
    {
        public int PortalDesktopModuleID { get; set; }
        public int PortalID { get; set; }
        public int DesktopModuleID { get; set; }
    
        public virtual dnn_DesktopModules dnn_DesktopModules { get; set; }
        public virtual dnn_Portals dnn_Portals { get; set; }
    }
}
