//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dotnetnukeEntities : DbContext
    {
        public dotnetnukeEntities()
            : base("name=dotnetnukeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<dnn_Affiliates> dnn_Affiliates { get; set; }
        public DbSet<dnn_Announcements> dnn_Announcements { get; set; }
        public DbSet<dnn_AnonymousUsers> dnn_AnonymousUsers { get; set; }
        public DbSet<dnn_Assemblies> dnn_Assemblies { get; set; }
        public DbSet<dnn_Authentication> dnn_Authentication { get; set; }
        public DbSet<dnn_Banners> dnn_Banners { get; set; }
        public DbSet<dnn_Blog_Blogs> dnn_Blog_Blogs { get; set; }
        public DbSet<dnn_Blog_Comments> dnn_Blog_Comments { get; set; }
        public DbSet<dnn_Blog_Entries> dnn_Blog_Entries { get; set; }
        public DbSet<dnn_Blog_Settings> dnn_Blog_Settings { get; set; }
        public DbSet<dnn_Classification> dnn_Classification { get; set; }
        public DbSet<dnn_DesktopModules> dnn_DesktopModules { get; set; }
        public DbSet<dnn_Documents> dnn_Documents { get; set; }
        public DbSet<dnn_DocumentsSettings> dnn_DocumentsSettings { get; set; }
        public DbSet<dnn_EventLog> dnn_EventLog { get; set; }
        public DbSet<dnn_EventLogConfig> dnn_EventLogConfig { get; set; }
        public DbSet<dnn_EventLogTypes> dnn_EventLogTypes { get; set; }
        public DbSet<dnn_EventQueue> dnn_EventQueue { get; set; }
        public DbSet<dnn_Events> dnn_Events { get; set; }
        public DbSet<dnn_EventsCategory> dnn_EventsCategory { get; set; }
        public DbSet<dnn_EventsLocation> dnn_EventsLocation { get; set; }
        public DbSet<dnn_EventsMaster> dnn_EventsMaster { get; set; }
        public DbSet<dnn_EventsNotification> dnn_EventsNotification { get; set; }
        public DbSet<dnn_EventsPPErrorLog> dnn_EventsPPErrorLog { get; set; }
        public DbSet<dnn_EventsSignups> dnn_EventsSignups { get; set; }
        public DbSet<dnn_FAQs> dnn_FAQs { get; set; }
        public DbSet<dnn_FAQsCategory> dnn_FAQsCategory { get; set; }
        public DbSet<dnn_Feedback> dnn_Feedback { get; set; }
        public DbSet<dnn_FeedbackList> dnn_FeedbackList { get; set; }
        public DbSet<dnn_Files> dnn_Files { get; set; }
        public DbSet<dnn_FolderPermission> dnn_FolderPermission { get; set; }
        public DbSet<dnn_Folders> dnn_Folders { get; set; }
        public DbSet<dnn_grmRepositoryAttributes> dnn_grmRepositoryAttributes { get; set; }
        public DbSet<dnn_grmRepositoryAttributeValues> dnn_grmRepositoryAttributeValues { get; set; }
        public DbSet<dnn_grmRepositoryCategories> dnn_grmRepositoryCategories { get; set; }
        public DbSet<dnn_grmRepositoryComments> dnn_grmRepositoryComments { get; set; }
        public DbSet<dnn_grmRepositoryObjectCategories> dnn_grmRepositoryObjectCategories { get; set; }
        public DbSet<dnn_grmRepositoryObjects> dnn_grmRepositoryObjects { get; set; }
        public DbSet<dnn_grmRepositoryObjectValues> dnn_grmRepositoryObjectValues { get; set; }
        public DbSet<dnn_Help_Category> dnn_Help_Category { get; set; }
        public DbSet<dnn_Help_TutorialCategory> dnn_Help_TutorialCategory { get; set; }
        public DbSet<dnn_Help_Tutorials> dnn_Help_Tutorials { get; set; }
        public DbSet<dnn_HostSettings> dnn_HostSettings { get; set; }
        public DbSet<dnn_HtmlText> dnn_HtmlText { get; set; }
        public DbSet<dnn_IFrame_Parameters> dnn_IFrame_Parameters { get; set; }
        public DbSet<dnn_Links> dnn_Links { get; set; }
        public DbSet<dnn_Lists> dnn_Lists { get; set; }
        public DbSet<dnn_Media> dnn_Media { get; set; }
        public DbSet<dnn_ModuleControls> dnn_ModuleControls { get; set; }
        public DbSet<dnn_ModuleDefinitions> dnn_ModuleDefinitions { get; set; }
        public DbSet<dnn_ModulePermission> dnn_ModulePermission { get; set; }
        public DbSet<dnn_Modules> dnn_Modules { get; set; }
        public DbSet<dnn_ModuleSettings> dnn_ModuleSettings { get; set; }
        public DbSet<dnn_MyLog> dnn_MyLog { get; set; }
        public DbSet<dnn_Packages> dnn_Packages { get; set; }
        public DbSet<dnn_PackageTypes> dnn_PackageTypes { get; set; }
        public DbSet<dnn_Permission> dnn_Permission { get; set; }
        public DbSet<dnn_PortalAlias> dnn_PortalAlias { get; set; }
        public DbSet<dnn_PortalDesktopModules> dnn_PortalDesktopModules { get; set; }
        public DbSet<dnn_Portals> dnn_Portals { get; set; }
        public DbSet<dnn_Profile> dnn_Profile { get; set; }
        public DbSet<dnn_ProfilePropertyDefinition> dnn_ProfilePropertyDefinition { get; set; }
        public DbSet<dnn_RoleGroups> dnn_RoleGroups { get; set; }
        public DbSet<dnn_Roles> dnn_Roles { get; set; }
        public DbSet<dnn_Schedule> dnn_Schedule { get; set; }
        public DbSet<dnn_ScheduleHistory> dnn_ScheduleHistory { get; set; }
        public DbSet<dnn_ScheduleItemSettings> dnn_ScheduleItemSettings { get; set; }
        public DbSet<dnn_SearchCommonWords> dnn_SearchCommonWords { get; set; }
        public DbSet<dnn_SearchIndexer> dnn_SearchIndexer { get; set; }
        public DbSet<dnn_SearchItem> dnn_SearchItem { get; set; }
        public DbSet<dnn_SearchItemWord> dnn_SearchItemWord { get; set; }
        public DbSet<dnn_SearchItemWordPosition> dnn_SearchItemWordPosition { get; set; }
        public DbSet<dnn_SearchWord> dnn_SearchWord { get; set; }
        public DbSet<dnn_SiteLog> dnn_SiteLog { get; set; }
        public DbSet<dnn_Skins> dnn_Skins { get; set; }
        public DbSet<dnn_SurveyOptions> dnn_SurveyOptions { get; set; }
        public DbSet<dnn_SurveyResults> dnn_SurveyResults { get; set; }
        public DbSet<dnn_Surveys> dnn_Surveys { get; set; }
        public DbSet<dnn_SystemMessages> dnn_SystemMessages { get; set; }
        public DbSet<dnn_TabModules> dnn_TabModules { get; set; }
        public DbSet<dnn_TabModuleSettings> dnn_TabModuleSettings { get; set; }
        public DbSet<dnn_TabPermission> dnn_TabPermission { get; set; }
        public DbSet<dnn_Tabs> dnn_Tabs { get; set; }
        public DbSet<dnn_UrlLog> dnn_UrlLog { get; set; }
        public DbSet<dnn_Urls> dnn_Urls { get; set; }
        public DbSet<dnn_UrlTracking> dnn_UrlTracking { get; set; }
        public DbSet<dnn_UserAuthentication> dnn_UserAuthentication { get; set; }
        public DbSet<dnn_UserDefinedData> dnn_UserDefinedData { get; set; }
        public DbSet<dnn_UserDefinedFields> dnn_UserDefinedFields { get; set; }
        public DbSet<dnn_UserDefinedRows> dnn_UserDefinedRows { get; set; }
        public DbSet<dnn_UserPortals> dnn_UserPortals { get; set; }
        public DbSet<dnn_UserProfile> dnn_UserProfile { get; set; }
        public DbSet<dnn_UserRoles> dnn_UserRoles { get; set; }
        public DbSet<dnn_Users> dnn_Users { get; set; }
        public DbSet<dnn_UsersOnline> dnn_UsersOnline { get; set; }
        public DbSet<dnn_VendorClassification> dnn_VendorClassification { get; set; }
        public DbSet<dnn_Vendors> dnn_Vendors { get; set; }
        public DbSet<dnn_Version> dnn_Version { get; set; }
        public DbSet<dnn_Wiki_CommentParents> dnn_Wiki_CommentParents { get; set; }
        public DbSet<dnn_Wiki_Comments> dnn_Wiki_Comments { get; set; }
        public DbSet<dnn_Wiki_Settings> dnn_Wiki_Settings { get; set; }
        public DbSet<dnn_Wiki_Topic> dnn_Wiki_Topic { get; set; }
        public DbSet<dnn_Wiki_TopicHistory> dnn_Wiki_TopicHistory { get; set; }
        public DbSet<dnn_Xml_Parameter> dnn_Xml_Parameter { get; set; }
        public DbSet<dnn_YourCompany_HelloWorld> dnn_YourCompany_HelloWorld { get; set; }
        public DbSet<dnn_YourCompany_LogEntry> dnn_YourCompany_LogEntry { get; set; }
        public DbSet<Meljab_HappyCustomers> Meljab_HappyCustomers { get; set; }
        public DbSet<orch_Common_BodyPartRecord> orch_Common_BodyPartRecord { get; set; }
        public DbSet<orch_Common_CommonPartRecord> orch_Common_CommonPartRecord { get; set; }
        public DbSet<orch_Common_CommonPartVersionRecord> orch_Common_CommonPartVersionRecord { get; set; }
        public DbSet<orch_Common_IdentityPartRecord> orch_Common_IdentityPartRecord { get; set; }
        public DbSet<orch_Containers_ContainablePartRecord> orch_Containers_ContainablePartRecord { get; set; }
        public DbSet<orch_Containers_ContainerPartRecord> orch_Containers_ContainerPartRecord { get; set; }
        public DbSet<orch_Containers_ContainerWidgetPartRecord> orch_Containers_ContainerWidgetPartRecord { get; set; }
        public DbSet<orch_Containers_CustomPropertiesPartRecord> orch_Containers_CustomPropertiesPartRecord { get; set; }
        public DbSet<orch_Navigation_AdminMenuPartRecord> orch_Navigation_AdminMenuPartRecord { get; set; }
        public DbSet<orch_Navigation_ContentMenuItemPartRecord> orch_Navigation_ContentMenuItemPartRecord { get; set; }
        public DbSet<orch_Navigation_MenuItemPartRecord> orch_Navigation_MenuItemPartRecord { get; set; }
        public DbSet<orch_Navigation_MenuPartRecord> orch_Navigation_MenuPartRecord { get; set; }
        public DbSet<orch_Navigation_MenuWidgetPartRecord> orch_Navigation_MenuWidgetPartRecord { get; set; }
        public DbSet<orch_Orchard_Alias_ActionRecord> orch_Orchard_Alias_ActionRecord { get; set; }
        public DbSet<orch_Orchard_Alias_AliasRecord> orch_Orchard_Alias_AliasRecord { get; set; }
        public DbSet<orch_Orchard_Autoroute_AutoroutePartRecord> orch_Orchard_Autoroute_AutoroutePartRecord { get; set; }
        public DbSet<orch_Orchard_Framework_ContentItemRecord> orch_Orchard_Framework_ContentItemRecord { get; set; }
        public DbSet<orch_Orchard_Framework_ContentItemVersionRecord> orch_Orchard_Framework_ContentItemVersionRecord { get; set; }
        public DbSet<orch_Orchard_Framework_ContentTypeRecord> orch_Orchard_Framework_ContentTypeRecord { get; set; }
        public DbSet<orch_Orchard_Framework_CultureRecord> orch_Orchard_Framework_CultureRecord { get; set; }
        public DbSet<orch_Orchard_Framework_DataMigrationRecord> orch_Orchard_Framework_DataMigrationRecord { get; set; }
        public DbSet<orch_Orchard_Packaging_PackagingSource> orch_Orchard_Packaging_PackagingSource { get; set; }
        public DbSet<orch_Orchard_Roles_PermissionRecord> orch_Orchard_Roles_PermissionRecord { get; set; }
        public DbSet<orch_Orchard_Roles_RoleRecord> orch_Orchard_Roles_RoleRecord { get; set; }
        public DbSet<orch_Orchard_Roles_RolesPermissionsRecord> orch_Orchard_Roles_RolesPermissionsRecord { get; set; }
        public DbSet<orch_Orchard_Roles_UserRolesPartRecord> orch_Orchard_Roles_UserRolesPartRecord { get; set; }
        public DbSet<orch_Orchard_Themes_ThemeSiteSettingsPartRecord> orch_Orchard_Themes_ThemeSiteSettingsPartRecord { get; set; }
        public DbSet<orch_Orchard_Users_RegistrationSettingsPartRecord> orch_Orchard_Users_RegistrationSettingsPartRecord { get; set; }
        public DbSet<orch_Orchard_Users_UserPartRecord> orch_Orchard_Users_UserPartRecord { get; set; }
        public DbSet<orch_Scheduling_ScheduledTaskRecord> orch_Scheduling_ScheduledTaskRecord { get; set; }
        public DbSet<orch_Settings_ContentFieldDefinitionRecord> orch_Settings_ContentFieldDefinitionRecord { get; set; }
        public DbSet<orch_Settings_ContentPartDefinitionRecord> orch_Settings_ContentPartDefinitionRecord { get; set; }
        public DbSet<orch_Settings_ContentPartFieldDefinitionRecord> orch_Settings_ContentPartFieldDefinitionRecord { get; set; }
        public DbSet<orch_Settings_ContentTypeDefinitionRecord> orch_Settings_ContentTypeDefinitionRecord { get; set; }
        public DbSet<orch_Settings_ContentTypePartDefinitionRecord> orch_Settings_ContentTypePartDefinitionRecord { get; set; }
        public DbSet<orch_Settings_ShellDescriptorRecord> orch_Settings_ShellDescriptorRecord { get; set; }
        public DbSet<orch_Settings_ShellFeatureRecord> orch_Settings_ShellFeatureRecord { get; set; }
        public DbSet<orch_Settings_ShellFeatureStateRecord> orch_Settings_ShellFeatureStateRecord { get; set; }
        public DbSet<orch_Settings_ShellParameterRecord> orch_Settings_ShellParameterRecord { get; set; }
        public DbSet<orch_Settings_ShellStateRecord> orch_Settings_ShellStateRecord { get; set; }
        public DbSet<orch_Settings_SiteSettings2PartRecord> orch_Settings_SiteSettings2PartRecord { get; set; }
        public DbSet<orch_Settings_SiteSettingsPartRecord> orch_Settings_SiteSettingsPartRecord { get; set; }
        public DbSet<orch_Title_TitlePartRecord> orch_Title_TitlePartRecord { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<dnn_vw_FolderPermissions> dnn_vw_FolderPermissions { get; set; }
        public DbSet<dnn_vw_Lists> dnn_vw_Lists { get; set; }
        public DbSet<dnn_vw_ModulePermissions> dnn_vw_ModulePermissions { get; set; }
        public DbSet<dnn_vw_Modules> dnn_vw_Modules { get; set; }
        public DbSet<dnn_vw_Portals> dnn_vw_Portals { get; set; }
        public DbSet<dnn_vw_TabPermissions> dnn_vw_TabPermissions { get; set; }
        public DbSet<dnn_vw_Tabs> dnn_vw_Tabs { get; set; }
        public DbSet<dnn_vw_Users> dnn_vw_Users { get; set; }
        public DbSet<vw_aspnet_Applications> vw_aspnet_Applications { get; set; }
        public DbSet<vw_aspnet_MembershipUsers> vw_aspnet_MembershipUsers { get; set; }
        public DbSet<vw_aspnet_Profiles> vw_aspnet_Profiles { get; set; }
        public DbSet<vw_aspnet_Roles> vw_aspnet_Roles { get; set; }
        public DbSet<vw_aspnet_Users> vw_aspnet_Users { get; set; }
        public DbSet<vw_aspnet_UsersInRoles> vw_aspnet_UsersInRoles { get; set; }
    }
}
