//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class orch_Containers_ContainerPartRecord
    {
        public int Id { get; set; }
        public Nullable<bool> Paginated { get; set; }
        public Nullable<int> PageSize { get; set; }
        public string OrderByProperty { get; set; }
        public Nullable<int> OrderByDirection { get; set; }
        public string ItemContentType { get; set; }
        public Nullable<bool> ItemsShown { get; set; }
    }
}
