//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class orch_Navigation_MenuWidgetPartRecord
    {
        public int Id { get; set; }
        public Nullable<int> StartLevel { get; set; }
        public Nullable<int> Levels { get; set; }
        public Nullable<bool> Breadcrumb { get; set; }
        public Nullable<bool> AddHomePage { get; set; }
        public Nullable<bool> AddCurrentPage { get; set; }
        public Nullable<int> Menu_id { get; set; }
    }
}
