//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class orch_Settings_ShellFeatureStateRecord
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string InstallState { get; set; }
        public string EnableState { get; set; }
        public Nullable<int> ShellStateRecord_Id { get; set; }
    }
}
