//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class orch_Orchard_Roles_RolesPermissionsRecord
    {
        public int Id { get; set; }
        public Nullable<int> Role_id { get; set; }
        public Nullable<int> Permission_id { get; set; }
        public Nullable<int> RoleRecord_Id { get; set; }
    }
}
