//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class orch_Containers_ContainerWidgetPartRecord
    {
        public int Id { get; set; }
        public Nullable<int> ContainerId { get; set; }
        public Nullable<int> PageSize { get; set; }
        public string OrderByProperty { get; set; }
        public Nullable<int> OrderByDirection { get; set; }
        public Nullable<bool> ApplyFilter { get; set; }
        public string FilterByProperty { get; set; }
        public string FilterByOperator { get; set; }
        public string FilterByValue { get; set; }
    }
}
