//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class orch_Common_CommonPartVersionRecord
    {
        public int Id { get; set; }
        public Nullable<int> ContentItemRecord_id { get; set; }
        public Nullable<System.DateTime> CreatedUtc { get; set; }
        public Nullable<System.DateTime> PublishedUtc { get; set; }
        public Nullable<System.DateTime> ModifiedUtc { get; set; }
    }
}
