//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class orch_Settings_SiteSettingsPartRecord
    {
        public int Id { get; set; }
        public string SiteSalt { get; set; }
        public string SiteName { get; set; }
        public string SuperUser { get; set; }
        public string PageTitleSeparator { get; set; }
        public string HomePage { get; set; }
        public string SiteCulture { get; set; }
        public string ResourceDebugMode { get; set; }
        public Nullable<int> PageSize { get; set; }
        public string SiteTimeZone { get; set; }
    }
}
