//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class orch_Orchard_Alias_AliasRecord
    {
        public int Id { get; set; }
        public string Path { get; set; }
        public Nullable<int> Action_id { get; set; }
        public string RouteValues { get; set; }
        public string Source { get; set; }
    }
}
