//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class orch_Orchard_Users_RegistrationSettingsPartRecord
    {
        public int Id { get; set; }
        public Nullable<bool> UsersCanRegister { get; set; }
        public Nullable<bool> UsersMustValidateEmail { get; set; }
        public string ValidateEmailRegisteredWebsite { get; set; }
        public string ValidateEmailContactEMail { get; set; }
        public Nullable<bool> UsersAreModerated { get; set; }
        public Nullable<bool> NotifyModeration { get; set; }
        public string NotificationsRecipients { get; set; }
        public Nullable<bool> EnableLostPassword { get; set; }
    }
}
