//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class orch_Containers_CustomPropertiesPartRecord
    {
        public int Id { get; set; }
        public string CustomOne { get; set; }
        public string CustomTwo { get; set; }
        public string CustomThree { get; set; }
    }
}
