//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domain_meljab
{
    using System;
    using System.Collections.Generic;
    
    public partial class orch_Orchard_Framework_ContentItemVersionRecord
    {
        public int Id { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<bool> Published { get; set; }
        public Nullable<bool> Latest { get; set; }
        public string Data { get; set; }
        public int ContentItemRecord_id { get; set; }
    }
}
